{
 "title": "Dgraph",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Zero and Alpha",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "dgraph_alpha_health_status{instance=~'$Instance'}-1"
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dgraph_alpha_health_status{instance=~'$Instance'}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(dgraph_memory_idle_bytes{instance=~'$Instance'}+dgraph_memory_inuse_bytes{instance=~'$Instance'})",
     "legendFormat": "Alpha"
    }
   ]
  },
  {
   "title": "Query stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  },
  {
   "title": "Dgraph Query and Mutation Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (method) (rate(dgraph_num_queries_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dgraph_num_queries_total[5m])",
     "legendFormat": "{{instance}} Server.Query"
    }
   ]
  },
  {
   "title": "Pending Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(dgraph_pending_queries_total{instance=~'$Instance'}[5m])",
     "legendFormat": "Pending Queries {{instance}}"
    }
   ]
  },
  { "title": "Dgraph Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Max Assigned Timestamp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "dgraph_max_assigned_ts{instance=~'$Instance'}",
     "legendFormat": "MaxTxnTs {{instance}}"
    }
   ]
  },
  {
   "title": "Dgraph RAFT ApplyCh Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    { "expr": "dgraph_raft_applych_size" }
   ]
  },
  {
   "title": "Raft Applied Index",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dgraph_raft_applied_index{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Pending Proposals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "dgraph_pending_proposals_total{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "RAFT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Leader Changes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "dgraph_raft_leader_changes_total",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "RAFT Has Leader",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      { "expr": "dgraph_raft_has_leader", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "RAFT Is Leader",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      { "expr": "dgraph_raft_is_leader", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "dgraph_memory_inuse_bytes+dgraph_memory_idle_bytes{instance=~'$Instance'}",
       "legendFormat": "Inuse+Idle ({{instance}})"
      },
      {
       "expr": "dgraph_memory_proc_bytes{instance=~'$Instance'}",
       "legendFormat": "Proc ({{instance}})"
      },
      {
       "expr": "dgraph_memory_alloc_bytes{instance=~'$Instance'}",
       "legendFormat": "Alloc {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Heap Idle",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "dgraph_memory_idle_bytes{instance=~'$Instance'}"
      }
     ]
    },
    {
     "title": "Memory Heap In-Use",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "dgraph_memory_inuse_bytes{instance=~'$Instance'}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Total Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "(sum by (instance) (dgraph_disk_used_bytes{instance=\"$Instance\"})) / (sum by (instance) ( dgraph_disk_total_bytes{instance='$Instance'}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Used Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "dgraph_disk_used_bytes{instance='$Instance'}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}